#include "utils.h"
#include <stdio.h>
#include <errno.h>
#include <stdlib.h>

void die(const char *message)
{
    /**
     * errno is set by various c library functions when an error occurs, and it indicates the type of error that occurred
     * perror prints an error message to the standard error stream (stderr): a string is prepended to the error message generated by perror
     */
    if (errno)
    {
        perror(message);
    }
    else
    {
        printf("ERROR: %s\n", message);
    }
}

void safe_free(void **pp)
{
    /*
    free function does not check the pointer passed to see whether it is NULL
    Using a pointer to pointer allows us to modify the pointer passed. Using the void type allows all types of pointers to be passed
    We get a warning if we don't explicitly cast the pointer type to void when we call the function
    safeFree macro #define safeFree(p) safe_free((void**)&(p))
    */
    if (pp != NULL && *pp != NULL)
    {
        free(*pp);

        *pp = NULL;
    }
}